image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: stable-amd64nvidia

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
portal:
  enabled: true
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 5000
  rtmp:
    enabled: false
    ports:
      rtmp:
        protocol: TCP
        enabled: true
        port: 1935
        targetPort: 1935

ingress:
  rtmp:
    autoLink: true

frigate:
  mqtt:
    host: 192.168.1.7
    port: 1883
    authentitcated: false
    username: frigate
    password: querty321
  birdseye:
    enabled: true
    mode: motion
  cameras:
    - name: cam_patio
      objects:
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
      detect:
        height: 720
        width: 1280
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: rtsp://admin:ratapaloma@192.168.1.53/live
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - record
        - path: rtsp://admin:ratapaloma@192.168.1.53/live
          roles:
            - detect
            - rtmp
      record:
        enabled: True
      # Optional: timeout for highest scoring image before allowing it
      # to be replaced by a newer image. (default: shown below)
      best_image_timeout: 60
      snapshots:
        enabled: True
persistence:
  cache:
    enabled: true
    mountPath: "/tmp/cache"
    type: "emptyDir"
  shm:
    enabled: true
    mountPath: "/dev/shm"
    type: "emptyDir"
    medium: "Memory"
  media:
    enabled: true
    mountPath: "/media"
  coral:
    enabled: true
env:
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"